name: Test
on: [push, pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: Get today
        id: date
        run: echo "::set-output name=date::$(date + '%d')"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ steps.date.outputs.date }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.date.outputs.date }}
            ${{ runner.os }}
      - name: Lint
        run: |
          yarn install --ignore-optional
          yarn lint
  Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify succeed test
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
          username: Shuvi Test & Lint
          color: '#2ECC71'
          avatarUrl: https://avatars1.githubusercontent.com/u/18323202?s=128&v=4
          severity: info
          details: Test Succeeded!
      - name: Notify failed test
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
          username: Shuvi Test & Lint
          color: '#E74C3C'
          avatarUrl: https://avatars1.githubusercontent.com/u/18323202?s=128&v=4
          severity: error
          details: Failed to test & lint!
      - name: Notify cancelled test
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
          username: Shuvi Test & Lint
          color: '#f1e903'
          avatarUrl: https://avatars1.githubusercontent.com/u/18323202?s=128&v=4
          severity: warn
          details: Occured somethings blocked test or was cancelled!
