name: Test
on: [push, pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}
      - name: Lint
        run: |
          yarn install --ignore-optional
          yarn lint
  Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: rjstone/discord-webhook-notify@v1
        if: always()
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
          username: Shuvi Test & Lint
          color: '#0099cc'
          avatarUrl: https://avatars1.githubusercontent.com/u/18323202?s=128&v=4
        if: success()
        with:
          severity: info
          details: Test Succeeded!
        if: failure()
        with:
          severity: error
          details: Failed to test & lint!
        if: cancelled()
        with:
          severity: warn
          details: Occured somethings blocked test or was cancelled!
