name: Test
on: [push, pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.JS 14.x
        uses: actions/setup-node@v1
        with:
          node_version: 14.2
      - name: Lint
        run: |
          npm run lint
