name: Test
on: [push, pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.JS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}
      - name: Lint
        run: |
          npm install
          npm run lint
